#!/bin/bash
source /usr/share/yunohost/helpers

ynh_script_progression --message="Arrêt et suppression du service..." --weight=1
ynh_systemd_action --service_name="$app" --action="stop"
yunohost service remove "$app"
ynh_remove_systemd_config
ynh_remove_nginx_config

ynh_script_progression --message="SCM Vidi désinstallé." --last
