#!/bin/bash
source /usr/share/yunohost/helpers

install_dir=$(ynh_app_setting_get --app=$app --key=install_dir)
data_dir=$(ynh_app_setting_get --app=$app --key=data_dir)

ynh_script_progression --message="Restauration des fichiers..." --weight=2
ynh_restore_file --origin_path="$install_dir"
ynh_restore_file --origin_path="$data_dir"

chown -R "$app:$app" "$install_dir"
chown -R "$app:$app" "$data_dir"

systemctl daemon-reload
ynh_systemd_action --service_name="$app" --action="enable"
ynh_systemd_action --service_name="$app" --action="start"
ynh_systemd_action --service_name=nginx --action=reload

ynh_script_progression --message="Restauration terminée !" --last
